### ISSUE TITLE
Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by machbio** [sohelamin/electron-vue-boilerplate#1]
While Running the Dev Server - the following error occurs;

```
Uncaught ReferenceError: require is not defined build.js:674
```

**Comment by sohelamin** [comment]
Did you run dev server before the application loaded?

I mean there need two terminals/tabs open one will serve the http server through `npm run dev-server` command and in another terminal `npm run dev`

**Comment by sohelamin** [comment]
@machbio Were you able to fix it?

**Comment by machbio** [comment]
@sohelamin thank you - I am pretty new to Electron - It did work. But when I tried to build it for Linux - the following error ocurred;

> electron-vue-boilerplate@0.0.1 package-linux /home/machbio/Projects/experimental/electron-vue-boilerplate
> electron-packager ./ --platform=linux --arch=ia32 --icon=assets/app.ico --out=package --asar=true --overwrite=force

module.js:341
    throw err;
    ^

Error: Cannot find module 'package.json'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:20:19)
    at getNameAndVersion (/home/machbio/Projects/experimental/electron-vue-boilerplate/node_modules/electron-packager/index.js:52:13)
    at packager (/home/machbio/Projects/experimental/electron-vue-boilerplate/node_modules/electron-packager/index.js:207:3)
    at Object.<anonymous> (/home/machbio/Projects/experimental/electron-vue-boilerplate/node_modules/electron-packager/cli.js:22:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)

**Comment by sohelamin** [comment]
@machbio It should not thrown error on any machine because I use "cross-env"
